cleanup for video

diff --git a/.github/workflows/CargoHub-Test.yml b/.github/workflows/CargoHub-Test.yml
--- a/.github/workflows/CargoHub-Test.yml
+++ b/.github/workflows/CargoHub-Test.yml
@@ -35,7 +35,48 @@ jobs:
       run: bash RunTests.sh
       working-directory: ./CargoHub
 
-    # - name: Check test results
+    - name: Upload automatic test run results
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: test-run-results
+        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/TestResults/test_results.trx"
+      
+    - name: Upload our own test results
+      if: always()
+      uses: actions/upload-artifact@v3
+      with:
+        name: test-results
+        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/CargoHub.Tests"
+
+    - name: Fail workflow if tests failed
+      if: failure()
+      run: exit 1 
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+      
+
+      
+    # - name: Check test results and revert if failed
     #   if: failure()
     #   run: |
     #     echo "Tests failed. Reverting commit..."
@@ -60,50 +101,50 @@ jobs:
         
     #     # Apply the stashed changes (if there were any)
     #     git stash pop
-    - name: Upload test run results
-      if: always()
-      uses: actions/upload-artifact@v3
-      with:
-        name: test-run-results
-        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/TestResults/test_results.trx"
-      
-    - name: Upload test results
-      if: always()
-      uses: actions/upload-artifact@v3
-      with:
-        name: test-results
-        path: "/home/runner/work/CargoHub/CargoHub/CargoHub.Tests/CargoHub.Tests"
-
-    - name: Check test results and report status
-      if: always()
-      uses: actions/github-script@v6
-      with:
-        script: |
-          const testApiStatus = '${{ steps.test-api.outcome }}'; // Get the outcome of the Test API step
-
-          const status = testApiStatus === 'success' ? 'success' : 'failure';
-          const description = status === 'success' ? 'All tests passed!' : 'Some tests failed.';
-
-          // Create a check run instead of using createCommitStatus
-          const checkRun = await github.rest.checks.create({
-            owner: context.repo.owner,
-            repo: context.repo.repo,
-            name: 'Test API Status',
-            head_sha: context.sha,
-            status: 'completed',
-            conclusion: status,
-            output: {
-              title: 'Test API',
-              summary: description,
-            },
-          });
-
-          console.log('Check run created successfully', checkRun.data);
-      env:
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
 
 
-    - name: Fail workflow if tests failed
-      if: failure()
-      run: exit 1 
+
+
+
+
+
+
+
+
+
+
+
+
+
+      # - name: Check test results and report status
+      # if: always()
+      # uses: actions/github-script@v6
+      # with:
+      #   script: |
+      #     const testApiStatus = '${{ steps.test-api.outcome }}'; // Get the outcome of the Test API step
+
+      #     const status = testApiStatus === 'success' ? 'success' : 'failure';
+      #     const description = status === 'success' ? 'All tests passed!' : 'Some tests failed.';
+
+      #     // Create a check run instead of using createCommitStatus
+      #     const checkRun = await github.rest.checks.create({
+      #       owner: context.repo.owner,
+      #       repo: context.repo.repo,
+      #       name: 'Test API Status',
+      #       head_sha: context.sha,
+      #       status: 'completed',
+      #       conclusion: status,
+      #       output: {
+      #         title: 'Test API',
+      #         summary: description,
+      #       },
+      #     });
+
+      #     console.log('Check run created successfully', checkRun.data);
+      # env:
+      #   GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+
+
+
+          
